der-scrof/Models/Engenheiro.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace der_scrof.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engenheiro
    {
        public int Id { get; set; }
        public int PessoaId { get; set; }
        public string CREA { get; set; }
        public string Visto { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public bool Active { get; set; }
        public Nullable<int> EmpresaId { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Pessoa Pessoa { get; set; }
    }
}

der-scrof/Models/Pendencia.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace der_scrof.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pendencia
    {
        public int Id { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public Nullable<int> PessoaId { get; set; }
        public string Observacao { get; set; }
        public System.DateTime Validade { get; set; }
        public int SituacaoId { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public bool Active { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual Situacao Situacao { get; set; }
    }
}

der-scrof/Controllers/EngenheiroController.cs
using der_scrof.Models;
using System;
using PagedList;
using System.Data;
using System.Linq;
using System.Web.Mvc;

namespace der_scrof.Controllers
{
    public class EngenheiroController : Controller
    {
        private der_db db = new der_db();

        [HttpPost]
        public JsonResult Registrar()
        {
            Usuario usuario = UsuarioLogin.getUserInfo();
            if (Request.Params["CPF"] != null)
            {
                string CPF = Request.Params["CPF"];
                int EmpresaId = int.Parse(Request.Params["EmpresaId"]);
                Engenheiro engenheiro = db.Engenheiro.SingleOrDefault(r => r.Pessoa.CPF == CPF && r.EmpresaId == EmpresaId);

                if (engenheiro != null)
                {
                    if (engenheiro.Active == true)
                    {
                        engenheiro.Pessoa.Nome = Request.Params["Nome"];
                        //engenheiro.Pessoa.CPF = Request.Params["CPF"];
                        engenheiro.Pessoa.Email = Request.Params["Email"];
                        engenheiro.Pessoa.Telefone = Request.Params["Telefone"];
                        engenheiro.Pessoa.Celular = Request.Params["Celular"];
                        //engenheiro.EmpresaId = int.Parse(Request.Params["EmpresaId"]);

                        engenheiro.Pessoa.Updated = DateTime.Now;
                        engenheiro.Pessoa.UpdatedBy = usuario.USUARIO_ID;

                        engenheiro.CREA = Request.Params["CREA"];
                        engenheiro.Visto = Request.Params["Visto"];
                        engenheiro.Updated = DateTime.Now;
                        engenheiro.UpdatedBy = usuario.USUARIO_ID;

                        db.Entry(engenheiro).State = EntityState.Modified;
                        db.SaveChanges();
                    }
                    else
                    {
                        return Json("Engenheiro desativado!");
                    }
                }
                else if (engenheiro == null)
                {
                    Pessoa pessoa = db.Pessoa.SingleOrDefault(p => p.CPF == CPF);
                    if (pessoa == null)
                    {
                        pessoa = new Pessoa
                        {
                            Nome = Request.Params["Nome"],
                            CPF = Request.Params["CPF"],
                            Email = Request.Params["Email"],
                            Telefone = Request.Params["Telefone"],
                            Celular = Request.Params["Celular"],
                            Created = DateTime.Now,
                            Active = true,
                            CreatedBy = usuario.USUARIO_ID
                        };

                        db.Pessoa.Add(pessoa);
                        db.SaveChanges();
                    }
                    else
                    {
                        pessoa.Nome = Request.Params["Nome"];
                        pessoa.Email = Request.Params["Email"];
                        pessoa.Celular = Request.Params["Celular"];
                        pessoa.Telefone = Request.Params["Telefone"];

                        pessoa.Updated = DateTime.Now;
                        pessoa.UpdatedBy = usuario.USUARIO_ID;

                        db.Entry(pessoa).State = EntityState.Modified;
                        db.SaveChanges();
                    }

                    engenheiro = new Engenheiro
                    {
                        PessoaId = pessoa.Id,
                        EmpresaId = int.Parse(Request.Params["EmpresaId"]),
                        CREA = Request.Params["CREA"],
                        Visto = Request.Params["Visto"],
                        Created = DateTime.Now,
                        Active = true,
                        CreatedBy = usuario.USUARIO_ID
                    };

                    db.Engenheiro.Add(engenheiro);
                    db.SaveChanges();

                }
            }

            try
            {
                db.SaveChanges();
                return Json(true);
            }
            catch (Exception)
            {
                return Json(false);
            }
        }

        [HttpPost]
        public JsonResult Apagar()
        {
            if (Request.Params["Id"] != null)
            {
                Usuario usuario = UsuarioLogin.getUserInfo();
                int id = int.Parse(Request.Params["Id"]);

                Engenheiro engenheiro = db.Engenheiro.Find(id);
                if (engenheiro == null)
                {
                    return Json(false);
                }
                engenheiro.Active = false;
                engenheiro.Updated = DateTime.Now;
                engenheiro.UpdatedBy = usuario.USUARIO_ID;
            }
            try
            {
                db.SaveChanges();
                return Json(true);
            }
            catch (Exception)
            {
                return Json(false);
            }
        }

        [HttpGet]
        public JsonResult Lista()
        {
            int EmpresaId = int.Parse(Request.QueryString["Id"]);
            var engenheiros = db.Engenheiro.Where(r => r.EmpresaId == EmpresaId && r.Active == true).Select(e => new { e.Id, Engenheiro = e.Pessoa.Nome, e.CREA }
            ).ToList();

            return Json(engenheiros, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Ativar()
        {
            Usuario usuario = UsuarioLogin.getUserInfo();
            Engenheiro engenheiro = db.Engenheiro.Find(int.Parse(Request.Params["Id"]));
            if (engenheiro==null)
            {
                return Json(false);
            }

            engenheiro.Active = true;
            engenheiro.Updated = DateTime.Now;
            engenheiro.UpdatedBy = usuario.USUARIO_ID;

            try
            {
                db.SaveChanges();
                return Json(true);
            }
            catch (Exception)
            {
                return Json(false);
            }
        }

        [HttpGet]
        public JsonResult Pesquisar()
        {
            string CPF = Request.QueryString["CPF"];
            Engenheiro engenheiro;

            if (!string.IsNullOrEmpty(CPF))
            {
                int empresaId = int.Parse(Request.QueryString["EmpresaId"]);
                engenheiro = db.Engenheiro.SingleOrDefault(e => e.Pessoa.CPF == CPF && e.EmpresaId == empresaId && e.Active == true);
            }
            else
            {
                engenheiro = db.Engenheiro.Find(int.Parse(Request.QueryString["Id"]));
            }

            if (engenheiro != null)
            {
                var json = new
                {
                    Id = engenheiro.Id,
                    CPF = engenheiro.Pessoa.CPF,
                    Nome = engenheiro.Pessoa.Nome,
                    Email = engenheiro.Pessoa.Email,
                    Telefone = engenheiro.Pessoa.Telefone,
                    Celular = engenheiro.Pessoa.Celular,
                    CREA = engenheiro.CREA,
                    Visto = engenheiro.Visto
                };
                return Json(json, JsonRequestBehavior.AllowGet);
            }
            else
            {
                Pessoa pessoa = db.Pessoa.SingleOrDefault(p => p.CPF == CPF);
                if (pessoa != null)
                {
                    var json = new
                    {
                        Id = "",
                        CPF = pessoa.CPF,
                        Nome = pessoa.Nome,
                        Email = pessoa.Email,
                        Telefone = pessoa.Telefone,
                        Celular = pessoa.Celular,
                        CREA = "",
                        Visto = ""
                    };
                    return Json(json, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(0, JsonRequestBehavior.AllowGet);
                }
            }

        }

        public ActionResult Index(string sortOrder, string searchString, int? page)
        {
            //return View(db.Engenheiro.ToList().Where(x => x.Active == true));

            if (!(Request.HttpMethod == "GET"))
            {
                page = 1;
            }

            ViewBag.CurrentFilter = searchString;

            IQueryable<Engenheiro> engenheiros = db.Engenheiro.OrderBy(c => c.Pessoa.Nome);

            if (!String.IsNullOrEmpty(searchString))
            {
                engenheiros = engenheiros.Where(s => s.Pessoa.Nome.ToUpper().Contains(searchString.ToUpper()) || s.CREA.ToUpper().Contains(searchString.ToUpper()) || s.Pessoa.CPF.ToUpper().Contains(searchString.ToUpper()));
            }

            int pageSize = 15; // Registros por Página
            int pageNumber = (page ?? 1);

            return View(engenheiros.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Pendencias(int id)
        {
            Engenheiro engenheiro = db.Engenheiro.Find(id);
            if (engenheiro == null)
            {
                return HttpNotFound();
            }


            return View(engenheiro);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

    }
}

der-scrof/Views/Engenheiro/Index.cshtml
@model PagedList.IPagedList<der_scrof.Models.Engenheiro>
@{
    ViewBag.Title = "Engenheiros";
}

@Html.Partial("_IndexHeader")
@Html.Partial("_AlertMessage")

<table class="table table-bordered table-condensed table-striped">
    <tr>
        <th>Nome</th>
        <th class="span2">CREA</th>
        <th class="span2">Visto</th>
        <th class="span1">Ativo?</th>
        <th class="span1"></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.Pessoa.Nome) <span class="label ">Pendências @item.Pessoa.Pendencia.Where(c => c.Active == true && c.SituacaoId == 1).Count()</span></td>
            <td>@Html.DisplayFor(modelItem => item.CREA)</td>
            <td>@Html.DisplayFor(modelItem => item.Visto)</td>
            <td>@Html.DisplayFor(modelItem => item.Active)</td>
            <td>
                <a class="btn btn-small" href="Engenheiro/Pendencias/@item.Id" title="Adicionar Pendência"><i class="icon-tags"></i></a>
            </td>
        </tr>
    }
</table>
@Html.Partial("_Pagination")

<script>
    $(document).ready(function () {
    }); // END $(document)
</script>

der-scrof/Views/Engenheiro/Pendencias.cshtml
@model der_scrof.Models.Engenheiro
@{
    ViewBag.Title = "Pendências ";
}


@if (Model.Active==false)
{
    <div class="row">
        <div class="span10"></div>
        <div class="span2">
            <div class="btn" id="ativar-engenheiro">Ativar Engenheiro</div>
        </div>
    </div>
}

@Html.HiddenFor(m => m.Id)
<div class="row">
    <input type="hidden" id="EngenheiroId" />
    <div class="span6">
        
        <h3>Engenheiro responsavel</h3>
        <div class="row">
            <div class="span2">
                @Html.LabelFor(model => model.Pessoa.CPF)
                @Html.TextBoxFor(model => model.Pessoa.CPF, new { @class = "span2 cpf", @readonly = "readonly" })
            </div>
            <div class="span4">
                @Html.LabelFor(model => model.Pessoa.Nome)
                @Html.TextBoxFor(model => model.Pessoa.Nome, new { @class = "span4", @readonly = "readonly" })
            </div>
        </div>
        <div class="row">
            <div class="span4">
                @Html.LabelFor(model => model.Pessoa.Email)
                @Html.TextBoxFor(model => model.Pessoa.Email, new { @class = "span4 ", @readonly = "readonly" })
            </div>
            <div class="span2">
                @Html.LabelFor(model => model.Pessoa.Telefone)
                @Html.TextBoxFor(model => model.Pessoa.Telefone, new { @class = "span2 telefone", @readonly = "readonly" })
            </div>
        </div>
        <div class="row">
            <div class="span2">
                @Html.LabelFor(model => model.Pessoa.Celular)
                @Html.TextBoxFor(model => model.Pessoa.Celular, new { @class = "span2 telefone", @readonly = "readonly" })
            </div>
            <div class="span2">
                @Html.LabelFor(model => model.CREA)
                @Html.TextBoxFor(model => model.CREA, new { @class = "span2 ", @readonly = "readonly" })
            </div>
            <div class="span2">
                @Html.LabelFor(model => model.Visto)
                @Html.TextBoxFor(model => model.Visto, new { @class = "span2 ", @readonly = "readonly" })
            </div>
        </div>

    </div>
    <div class="span6">

        @using (Html.BeginForm("Criar", "Pendencia", FormMethod.Post))
        {             
            <h3>Pendências <div class="label " id="quantidadePendencias"></div></h3>   
            <div class="row">
                @Html.Hidden("PendenciaId")

                <div class="span2">
                    @Html.Label("Data final", new { @class = "text-error" })
                    @Html.TextBox("ValidadePendencia", "", new { @class = "span2 data" })
                </div>

                <div class="span6">
                    @Html.Label("Observação", new { @class = "text-error" })
                    @Html.TextArea("Observacao", "Nº Processo:\nÓrgão de origem:\nTipificação:\nMotivo:", 5, 63, new { @class = "span6 " })
                </div>
            </div>   
            <div class="row">
                <button type="button" id="AdicionarPendencia" class="btn btn-primary span3">Adicionar</button>
            </div>
        }
    </div>
</div>

<hr />
<h3>Pendências  Ativas</h3>
<table id="tablePendecias" class="table table-bordered table-condensed table-striped">
    <thead>
        <tr>
            <th class="">#</th>
            <th class="span2">Situação</th>
            <th class="span1">Data</th>
            <th class="span1">Validade</th>
            <th>Observação</th>
            <th class="botoes-tabela1">&nbsp;</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

<script>
    $(document).ready(function () {

        carregarTablePendencias();

        function carregarTablePendencias() {
            var EmpresaId = $('#Id').val();

            carregarQuantidadePendencias();

            $.ajax({
                type: 'GET', url: '@Url.Action("ListaPorEngenheiro", "Pendencia", null)', data: { Id: EmpresaId }
            }).done(function (data) {

                var template = Handlebars.compile($("#templateTablePendecias").html());
                var html = template(data);

                $('#tablePendecias').find('tbody').html(html);

            }).error(function (data) { console.log(data); });
        }

        function carregarQuantidadePendencias() {
            var EmpresaId = $('#Id').val();

            $.ajax({
                type: 'GET', url: '@Url.Action("QuantidadePendenciasEngenheiro", "Pendencia", null)', data: { Id: EmpresaId }
            }).done(function (data) {
                if (data < 1) {
                    $('#quantidadePendencias').html(data).addClass('label-success');
                }
                else if (data == 1 || data == 2) {
                    $('#quantidadePendencias').html(data).addClass('label-warning');
                }
                else if (data > 2) {
                    $('#quantidadePendencias').html(data).addClass('label-important');
                }
            }).error(function (data) { console.log(data); });
        }

        $('#tablePendecias').find('.btn-editar').live('click', function () {
            $this = $(this);

            $.ajax({
                type: 'GET', url: '@Url.Action("Pesquisar", "Pendencia", null)', data: { Id: $this.data('id') }
            }).done(function (data) {

                $('#SituacaoId').val(data.SituacaoId);
                $('#Observacao').val(data.Observacao);
                $('#PendenciaId').val(data.Id);

            }).error(function (data) { console.log(data); });
        });

        $('#tablePendecias').find('.btn-excluir').live('click', function () {
            $this = $(this);

            $.ajax({
                type: 'GET', url: '@Url.Action("Deletar", "Pendencia", null)', data: { Id: $this.data('id') }
            }).done(function (data) {

                if (data) {
                    alert('Pendência removida da empresa!');
                    carregarTablePendencias();
                }

            }).error(function (data) { console.log(data); });
        });

        $('#AdicionarPendencia').on('click', function () {
            var obj = {
                Id: $('#PendenciaId').val(),
                Observacao: $('#Observacao').val(),
                Validade: $('#ValidadePendencia').val(),
                EngenheiroId: $('#Id').val()
            };

            $.ajax({
                type: 'POST', url: '@Url.Action("Criar", "Pendencia", null)', data: obj
            }).done(function (data) {

                if (data) {
                    alert('Pendência salva ao engenheiro!');
                    carregarTablePendencias();

                    $('#ValidadePendencia').val("");
                    $('#Observacao').val("Nº Processo:\nÓrgão de origem:\nTipificação:\nMotivo:");
                    $('#PendenciaId').val("");
                }
            }).error(function (data) { console.log(data); });
        });

        $('#ativar-engenheiro').on('click', function () {
            var obj = {
                Id: $('#Id').val()
            };

            $.ajax({
                type: 'POST', url: '@Url.Action("Ativar", "Engenheiro", null)', data: obj
            }).done(function (data) {

                if (data) {
                    alert('Engenheiro ativado com sucesso!');

                    window.setTimeout("location.reolad()", 5000);
                }
            }).error(function (data) { console.log(data); });
        });

    }); // END $(document)
</script>

<script id="templateTablePendecias" type="text/x-handlebars-template">
    {{#each this}}
    <tr>
        <td><small>{{Id}}</small></td>
        <td><span class="label label-warning">{{Situacao}}</span> - {{setor}}</td>
        <td>{{Data}}</td>
        <td><span class="label label-important">até {{Validade}}</span></td>
        <td>{{{Pendencia}}}</td>
        <td>
            <div class="btn-group">
                <button type="button" data-id="{{Id}}" class="btn btn-excluir btn-mini btn-danger" title="Excluir"><i class="icon-remove icon-white"></i></button>
            </div>
        </td>
    </tr>
    {{/each}}
</script>